const OBJ_TYPES = [
  { id: 'floor', label: 'Floor', color: '#9b9b9c' },
  { id: 'wall', label: 'Wall', color: '#7a8a9c' },
  { id: 'lava', label: 'Lava', color: '#fc9312' },
  { id: 'trampoline', label: 'Trampoline', color: '#1264fc' },
  { id: 'enemy', label: 'Enemy', color: '#fc1212' },
  { id: 'orb', label: 'Orb', color: '#fce512' },
  { id: 'movingPlatformUp', label: 'MP Up', color: '#4caf50' },
  { id: 'movingPlatformRight', label: 'MP Right', color: '#26c6da' },
  { id: 'coin', label: 'Coin', color: '#ffd700' },
  { id: 'key', label: 'Key', color: '#f0b429' },
  { id: 'checkpoint', label: 'Checkpoint', color: '#4caf50' },
  { id: 'end', label: 'End', color: '#fce512' },
  { id: 'text', label: 'Text', color: '#ffffff' },
  { id: 'portal', label: 'Portal', color: '#a855f7' },
  { id: 'area', label: 'Area', color: '#00ffb4' },
  { id: 'camera', label: 'Camera', color: '#5b9cf6' },
  { id: 'music', label: 'Music Trigger', color: '#e879f9' },
  { id: 'enemySpawner', label: 'Enemy Spawner', color: '#fb923c' },
  { id: 'despawnEnemies', label: 'Despawn', color: '#f43f5e' },
];

const CMAP = {};
OBJ_TYPES.forEach(t => CMAP[t.id] = t.color);

const FDEFS = {
  floor: [
    ['Name', 'name:text'],
    ['Position', 'x:num,y:num'],
    ['Size', 'w:num,h:num'],
    ['Options', 'ghost:bool,oneWay:bool'],
    ['Texture', 'texture:tex,textureMode:tmode,textureFrames:num,textureFps:num,rotation:num,invertX:bool,invertY:bool'],
  ],
  wall: [
    ['Name', 'name:text'],
    ['Position', 'x:num,y:num'],
    ['Size', 'w:num,h:num'],
    ['Options', 'ghost:bool,opaque:bool'],
    ['Door', 'keyId:kref,keyColor:text,keyhole:khole,closeOnAreaId:aref'],
    ['Rise', 'riseWithId:text,riseYOnly:bool,riseYOffset:num'],
    ['Texture', 'texture:tex,textureGhost:tex,textureMode:tmode,textureFrames:num,textureFps:num,rotation:num,invertX:bool,invertY:bool'],
  ],
  lava: [
    ['Name', 'name:text'],
    ['Position', 'x:num,y:num'],
    ['Size', 'w:num,h:num'],
    ['Options', 'ghost:bool'],
    ['Flow', 'flowUp:bool,flowSpeed:num,flowDuration:num,flowAreaId:text,riseId:text'],
    ['Texture', 'texture:tex,textureMode:tmode,textureFrames:num,textureFps:num,rotation:num,invertX:bool,invertY:bool'],
  ],
  trampoline: [
    ['Name', 'name:text'],
    ['Position', 'x:num,y:num'],
    ['Size', 'w:num,h:num'],
    ['Options', 'ghost:bool,strength:num'],
    ['Texture', 'texture:tex,textureMode:tmode,textureFrames:num,textureFps:num,rotation:num,invertX:bool,invertY:bool'],
  ],
  enemy: [
    ['Name', 'name:text'],
    ['Position', 'x:num,y:num'],
    ['Bounds', 'min:num,max:num'],
    ['Options', 'ghost:bool,detectionRadius:num,stuck:bool'],
    ['Texture', 'texture:tex,textureMode:tmode,textureFrames:num,textureFps:num,rotation:num,invertX:bool,invertY:bool'],
  ],
  orb: [
    ['Name', 'name:text'],
    ['Position', 'x:num,y:num'],
    ['Options', 'r:num,strength:num,ghost:bool'],
    ['Texture', 'texture:tex,textureMode:tmode'],
  ],
  movingPlatformUp: [
    ['Name', 'name:text'],
    ['Position', 'x:num'],
    ['Size', 'w:num,h:num'],
    ['Range', 'startY:num,endY:num'],
    ['Trigger', 'triggerMode:bool,triggerTimeout:num,returnTimeout:num'],
    ['Options', 'ghost:bool,oneWay:bool'],
    ['Texture', 'texture:tex,textureMode:tmode,textureFrames:num,textureFps:num,rotation:num,invertX:bool,invertY:bool'],
  ],
  movingPlatformRight: [
    ['Name', 'name:text'],
    ['Position', 'y:num'],
    ['Size', 'w:num,h:num'],
    ['Range', 'startX:num,endX:num'],
    ['Options', 'ghost:bool,oneWay:bool'],
    ['Texture', 'texture:tex,textureMode:tmode,textureFrames:num,textureFps:num,rotation:num,invertX:bool,invertY:bool'],
  ],
  coin: [
    ['Name', 'name:text'],
    ['Position', 'x:num,y:num'],
    ['Options', 'r:num,blue:bool,ghost:bool'],
    ['Texture', 'texture:tex,textureMode:tmode'],
  ],
  key: [
    ['Name', 'name:text'],
    ['Position', 'x:num,y:num'],
    ['Options', 'r:num,keyId:kid,color:text,ghost:bool'],
  ],
  checkpoint: [['Name', 'name:text'], ['Position', 'x:num,y:num']],
  end: [['Name', 'name:text'], ['Position', 'x:num,y:num'], ['Size', 'w:num,h:num']],
  text: [
    ['Name', 'name:text'],
    ['Position', 'x:num,y:num'],
    ['Content', 'content:richtext'],
    ['Style', 'color:text,font:text'],
    ['Options', 'ghost:bool'],
  ],
  portal: [
    ['Name', 'name:text'],
    ['Position', 'x:num,y:num'],
    ['Size', 'w:num,h:num'],
    ['Portal', 'portal-id:pid,to-portal-id:pref'],
    ['Texture', 'texture:tex,textureMode:tmode,textureFrames:num,textureFps:num,rotation:num,invertX:bool,invertY:bool'],
  ],
  area: [
    ['Name', 'name:text'],
    ['Position', 'x:num,y:num'],
    ['Size', 'w:num,h:num'],
    ['Options', 'id:aid,checkpointX:num,checkpointY:num'],
  ],
  camera: [
    ['Name', 'name:text'],
    ['Position', 'x:num,y:num'],
    ['Options', 'areaId:aref,lockX:bool,lockY:bool,targetCamX:num,targetCamY:num'],
  ],
  music: [
    ['Name', 'name:text'],
    ['Position', 'x:num,y:num'],
    ['Options', 'areaId:aref,song:text,fadeDuration:num,restartOnDie:bool'],
  ],
  enemySpawner: [
    ['Name', 'name:text'],
    ['Position', 'x:num,y:num'],
    ['Size', 'w:num,h:num'],
    ['Options', 'areaId:aref,count:num,spread:num,detectionRadius:num,speed:num,stuck:bool'],
    ['Texture', 'texture:tex,textureMode:tmode,textureFrames:num,textureFps:num,rotation:num,invertX:bool,invertY:bool'],
  ],
  despawnEnemies: [
    ['Name', 'name:text'],
    ['Position', 'x:num,y:num'],
    ['Options', 'areaId:aref,spawnerAreaId:aref'],
  ],
};

const SHORTCUTS = [
  ['Select', 'V'],
  ['Place', 'P'],
  ['Pan', 'H'],
  ['Multi-select', 'Shift+click'],
  ['Box select', 'Shift+drag'],
  ['Undo', 'Ctrl+Z'],
  ['Redo', 'Ctrl+Y'],
  ['Duplicate', 'Ctrl+D'],
  ['Copy', 'Ctrl+C'],
  ['Paste', 'Ctrl+V'],
  ['Group', 'Ctrl+G'],
  ['Delete', 'Del'],
  ['Deselect', 'Escape'],
  ['Nudge 1px', 'Arrow'],
  ['Nudge 10px', 'Shift+Arrow'],
  ['Move up', ']'],
  ['Move down', '['],
  ['Fit', 'Ctrl+0'],
  ['Focus selected', 'F'],
  ['Zoom', 'Scroll'],
  ['Pan', 'Space+drag'],
  ['Shortcuts', '?'],
];

const EXPORT_ORDER = [
  'name', 'x', 'y', 'w', 'h', 'r', 'startY', 'endY', 'startX', 'endX',
  'ghost', 'oneWay', 'opaque',
  'texture', 'textureGhost', 'textureMode', 'textureFrames', 'textureFps', 'rotation', 'invertX', 'invertY',
  'keyId', 'keyColor', 'keyhole', 'closeOnAreaId',
  'riseWithId', 'riseYOnly', 'riseYOffset',
  'flowUp', 'flowSpeed', 'flowDuration', 'flowAreaId', 'riseId',
  'strength', 'min', 'max', 'detectionRadius', 'stuck', 'blue', 'color', 'font', 'content',
  'portal-id', 'to-portal-id',
  'id', 'areaId', 'spawnerAreaId',
  'count', 'spread', 'speed',
  'lockX', 'lockY', 'targetCamX', 'targetCamY',
  'song', 'fadeDuration', 'restartOnDie',
  'checkpointX', 'checkpointY',
  'triggerMode', 'triggerTimeout', 'returnTimeout',
];

const TAG_COLORS = {
  y: '#fce512',
  r: '#fc1212',
  g: '#4caf50',
  bl: '#5b9cf6',
  o: '#fc9312',
  p: '#c084fc',
  w: '#ffffff',
  gray: '#9b9b9c',
};